ViewModels/Account/VolunteerViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Version1.Models;

namespace Version1.ViewModels.Account
{
    public class VolunteerViewModel
    {
        public List<Version1.Models.Team> viewTeams { get; set; }
        public ApplicationUser viewVolunteers { get; set; }
        public List<TeamMember> viewTeam_mumbers { get; set; }
    }
}

Areas/Management/Controllers/VolunteerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Version1.Models;
using Version1.ViewModels.RoleManage;
using Microsoft.Net.Http.Headers;
using Microsoft.AspNetCore.Hosting;
using System.IO;
namespace Version1.Controllers
{
    [Area("Management")]
  //  [Authorize(Roles = "manager")]
    public class VolunteerController : Controller
    {
        Version1.ViewModels.Account.VolunteerViewModel viewModel = new Version1.ViewModels.Account.VolunteerViewModel();
        private readonly ApplicationDbContext _context;
        private IHostingEnvironment hostingEnv;
        public VolunteerController(IHostingEnvironment env, ApplicationDbContext context)
        {
            this.hostingEnv = env;
            _context = context;
        }

        // GET: Volunteer
        public async Task<IActionResult> Index()
        {
            return View(await _context.ApplicationUser.OrderByDescending(p=>p.RegisterationDatetime).ToListAsync());
        }

        // GET: Volunteer/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if(id == null)
            {
                return NotFound();
            }

            var applicationUser = await _context.ApplicationUser.SingleOrDefaultAsync(m => m.Id == id);
            if(applicationUser == null)
            {
                return NotFound();
            }

            viewModel.viewTeams = _context.Teams.ToList();
            viewModel.viewVolunteers = applicationUser;
            viewModel.viewTeam_mumbers = _context.TeamMembers.ToList();
            return View(viewModel);
        }

        // GET: Volunteer/Create
        public IActionResult Create(string id)
        {
            if(id != null)
            {
                TempData["ppp"] = id;
            }
            return View();
        }

        // POST: Volunteer/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,gender,AccessFailedCount,Age,ConcurrencyStamp,Email,EmailConfirmed,FirstName,LastName,LockoutEnabled,LockoutEnd,NormalizedEmail,NormalizedUserName,PasswordHash,PhoneNumber,PhoneNumberConfirmed,SecurityStamp,TwoFactorEnabled,UserName,Portrait,RegisterationDatetime,UserState")] ApplicationUser applicationUser)
        {
            if(ModelState.IsValid)
            {
                
                //upload Newsletter image
                string ImageGUID = Guid.NewGuid().ToString();
                var file = Request.Form.Files[0];
                var filename = ContentDispositionHeaderValue.Parse(file.ContentDisposition).FileName.Trim('"');
                if (filename!="")
                {
                    filename = ImageGUID + filename.Substring(filename.Length - 4, 4);
                    applicationUser.Portrait = filename;
                    filename = hostingEnv.WebRootPath + $@"\images\portrait\{filename}";
                    using (FileStream fs = System.IO.File.Create(filename))
                    {
                        file.CopyTo(fs);
                        fs.Flush();
                    }
                }
                
                _context.Add(applicationUser);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(applicationUser);
        }

        // GET: Volunteer/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if(id == null)
            {
                return NotFound();
            }

            var applicationUser = await _context.ApplicationUser.SingleOrDefaultAsync(m => m.Id == id);
            if(applicationUser == null)
            {
                return NotFound();
            }
            return View(applicationUser);
        }

        // POST: Volunteer/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,gender,AccessFailedCount,Age,ConcurrencyStamp,Email,EmailConfirmed,FirstName,LastName,LockoutEnabled,LockoutEnd,NormalizedEmail,NormalizedUserName,PasswordHash,PhoneNumber,PhoneNumberConfirmed,SecurityStamp,TwoFactorEnabled,UserName,RegisterationDatetime,UserState")] ApplicationUser applicationUser)
        {
            if(id != applicationUser.Id)
            {
                return NotFound();
            }

            if(ModelState.IsValid)
            {
                try
                {
                    string oldimagepath = applicationUser.Portrait;
                    Boolean IfNewimage = false;
                    //upload Newsletter image                   
                    if (Request.Form.Files.Count > 0)
                    {
                        string ImageGUID = Guid.NewGuid().ToString();
                        var file = Request.Form.Files[0];
                        var filename = ContentDispositionHeaderValue.Parse(file.ContentDisposition).FileName.Trim('"');
                        if (filename != "")
                        {
                            filename = ImageGUID + filename.Substring(filename.Length - 4, 4);
                            applicationUser.Portrait = filename;
                            filename = hostingEnv.WebRootPath + $@"\images\portrait\{filename}";
                            using (FileStream fs = System.IO.File.Create(filename))
                            {
                                file.CopyTo(fs);
                                fs.Flush(); IfNewimage = true;
                            }
                        }
                            
                    }
                    _context.Update(applicationUser);
                    //delete old image
                    if (IfNewimage)
                    {
                        oldimagepath = hostingEnv.WebRootPath + $@"\images\portrait\{oldimagepath}";
                        if (System.IO.File.Exists(oldimagepath))
                        {
                            System.IO.File.Delete(oldimagepath);
                        }
                    }
                    await _context.SaveChangesAsync();
                }
                catch(DbUpdateConcurrencyException)
                {
                    if(!ApplicationUserExists(applicationUser.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(applicationUser);
        }

        // GET: Volunteer/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if(id == null)
            {
                return NotFound();
            }

            var applicationUser = await _context.ApplicationUser.SingleOrDefaultAsync(m => m.Id == id);
            if(applicationUser == null)
            {
                return NotFound();
            }

            return View(applicationUser);
        }

        // POST: Volunteer/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var applicationUser = await _context.ApplicationUser.SingleOrDefaultAsync(m => m.Id == id);
            string oldimagepath = applicationUser.Portrait;
            _context.ApplicationUser.Remove(applicationUser);
            await _context.SaveChangesAsync();
            //delete old image
            oldimagepath = hostingEnv.WebRootPath + $@"\images\portrait\{oldimagepath}";
            if (System.IO.File.Exists(oldimagepath))
            {
                try
                {
                    System.IO.File.Delete(oldimagepath);
                }
                catch (Exception)
                {
                    throw;
                }
            }
            return RedirectToAction("Index");
        }

        private bool ApplicationUserExists(string id)
        {
            return _context.ApplicationUser.Any(e => e.Id == id);
        }
    }
}

Areas/Management/Views/Volunteer/Create.cshtml
@model Version1.Models.ApplicationUser

 

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>

<form asp-area="Management" asp-controller="Volunteer"  asp-action="Create" enctype="multipart/form-data">
    <div class="form-horizontal">
        <h4>ApplicationUser</h4>
        <hr /> 
        <div class="form-group">
            <label asp-for="Portrait" class="col-md-2 control-label">portrait</label>
            <div class="col-md-10"><br>
                <input type="file" id="NewsImagepp" value="Open file" title="Open file" accept=".JPG,.JPEG,.GIF,.PNG,.bmp" name="NewsImagepp" />
             
                  <img id="opop" src="~/images/portrait/defaultportrait.png" align="left" width="190" height="210" display=inline>
            </div>
            <div class="form-group"></div>
            <div class="form-group">
                <label asp-for="gender" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <select asp-for="gender" class="form-control"><option>Male</option><option>Female</option></select>
                </div>
                <span asp-validation-for="gender" class="text-danger" />
            </div>
                <div class="form-group">
                    <label asp-for="Age" class="col-md-2 control-label"></label>
                    <div class="col-md-10">
                        <input asp-for="Age" class="form-control" />
                        <span asp-validation-for="Age" class="text-danger" />
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="Email" class="col-md-2 control-label"></label>
                    <div class="col-md-10">
                        <input asp-for="Email" class="form-control" />
                        <span asp-validation-for="Email" class="text-danger" />
                    </div>
                </div>

                <div class="form-group">
                    <label asp-for="FirstName" class="col-md-2 control-label"></label>
                    <div class="col-md-10">
                        <input asp-for="FirstName" class="form-control" />
                        <span asp-validation-for="FirstName" class="text-danger" />
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="LastName" class="col-md-2 control-label"></label>
                    <div class="col-md-10">
                        <input asp-for="LastName" class="form-control" />
                        <span asp-validation-for="LastName" class="text-danger" />
                    </div>
                </div>


                <div class="form-group">
                    <label asp-for="PhoneNumber" class="col-md-2 control-label"></label>
                    <div class="col-md-10">
                        <input asp-for="PhoneNumber" class="form-control" />
                        <span asp-validation-for="PhoneNumber" class="text-danger" />
                    </div>
                </div>


                <div class="form-group">
                    <label asp-for="UserName" class="col-md-2 control-label"></label>
                    <div class="col-md-10">
                        <input asp-for="UserName" class="form-control" />
                        <span asp-validation-for="UserName" class="text-danger" />
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
            </div>
</form>

<div>
    <a sp-area="Management" asp-controller="Volunteer" asp-action="Index">Back to List</a>
</div>


    @section Scripts {
        <script src="//code.jquery.com/jquery-1.12.4.min.js"></script>
        <script src="//rawgithub.com/indrimuska/jquery-editable-select/master/dist/jquery-editable-select.min.js"></script>
        <script src="/lib/ckeditor/ckeditor.js"></script>
        <link href="//rawgithub.com/indrimuska/jquery-editable-select/master/dist/jquery-editable-select.min.css" rel="stylesheet">


        <script>
    $(function () {
      
   var  getobjectpath= function (file) {
        var url = null;
        if (window.createObjectURL != undefined) {
            url = window.createObjectURL(file)
        } else if (window.URL != undefined) {
            url = window.URL.createObjectURL(file)
        } else if (window.webkitURL != undefined) {
            url = window.webkitURL.createObjectURL(file)
        }
        return url
    };
   $("#NewsImagepp").change(function () {
        var imagepath = getobjectpath(this.files[0]);
        if (imagepath != "") {
            $("#opop").attr('src', imagepath);
            $("#opop").fadeIn(1000);
        }
   });
    });
        </script>
    }
</body>
</html>

Areas/Management/Views/Volunteer/Delete.cshtml
@model Version1.Models.ApplicationUser

 

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ApplicationUser</h4>
    <hr />
    <dl class="dl-horizontal">
        <dd>
            <img src="~/images/Portrait/@Model.Portrait" align="left" width="190" height="210" display=inline>
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AccessFailedCount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AccessFailedCount)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ConcurrencyStamp)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ConcurrencyStamp)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EmailConfirmed)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EmailConfirmed)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LockoutEnabled)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LockoutEnabled)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LockoutEnd)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LockoutEnd)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NormalizedEmail)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NormalizedEmail)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NormalizedUserName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NormalizedUserName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PasswordHash)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PasswordHash)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumberConfirmed)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PhoneNumberConfirmed)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SecurityStamp)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SecurityStamp)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TwoFactorEnabled)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TwoFactorEnabled)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

    </dl>
    
    <form sp-area="Management" asp-controller="Volunteer" asp-action="Delete" asp-route-id="@Model.Id">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a sp-area="Management" asp-controller="Volunteer" asp-action="Index">Back to List</a>
        </div>
    </form>
</div>
</body>
</html>

Areas/Management/Views/Volunteer/Details.cshtml
@model Version1.ViewModels.Account.VolunteerViewModel 

 

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
 
<div class="body-content">
    <h4>ApplicationUser</h4><a sp-area="Management" asp-controller="Volunteer" asp-action="Edit" asp-route-id="@Model.viewVolunteers.Id">Edit</a> |
<a sp-area="Management" asp-controller="Volunteer" asp-action="Index">Back to List</a>
    <hr /><div class="col-lg-7" >

    <dl class="dl-horizontal">

        <dt>
             Access Failed Count 
        </dt>
        <dd>
            @Html.DisplayFor(model => model.viewVolunteers.AccessFailedCount)
        </dd>
        <dt>
           Gender
        </dt>
        <dd>
            @Html.DisplayFor(model => model.viewVolunteers.gender)
        </dd>
        <dt>
            Age
        </dt>
        <dd>
            @Html.DisplayFor(model => model.viewVolunteers.Age)
        </dd>
        
        <dt>
             Email 
        </dt>
        <dd>
            @Html.DisplayFor(model => model.viewVolunteers.Email)
        </dd>
        <dt>
             Email Confirmed 
        </dt>
        <dd>
            @Html.DisplayFor(model => model.viewVolunteers.EmailConfirmed)
        </dd>
        <dt>
             FirstName 
        </dt>
        <dd>
            @Html.DisplayFor(model => model.viewVolunteers.FirstName)
        </dd>
        <dt>
             LastName 
        </dt>
        <dd>
            @Html.DisplayFor(model => model.viewVolunteers.LastName)
        </dd>
        
        
        <dt>
             Normalized Email 
        </dt>
        <dd>
            @Html.DisplayFor(model => model.viewVolunteers.NormalizedEmail)
        </dd>
        <dt>
             Normalized UserName 
        </dt>
        <dd>
            @Html.DisplayFor(model => model.viewVolunteers.NormalizedUserName)
        </dd>
        
        <dt>
       Phone Number 
        </dt>
        <dd>
            @Html.DisplayFor(model => model.viewVolunteers.PhoneNumber)
        </dd>
        <dt>
           Phone Number Confirmed 
        </dt>
        <dd>
            @Html.DisplayFor(model => model.viewVolunteers.PhoneNumberConfirmed)
        </dd>
        
        <dt>
             Two Factor Enabled 
        </dt>
        <dd>
            @Html.DisplayFor(model => model.viewVolunteers.TwoFactorEnabled)
        </dd>
        <dt>
              UserName 
        </dt>
        <dd>
            @Html.DisplayFor(model => model.viewVolunteers.UserName)
        </dd>
        <dt>
            Teams In
        </dt>
       
        @{ string teamlist = ""; string teamid = ""; string teamname = "";} 
        @foreach (var item in Model.viewTeam_mumbers.Where(a => a.UserID == Model.viewVolunteers.Id))
        {
            teamid = item.TeamId;
            teamname = Model.viewTeams.Where(h => h.TeamId == teamid).First().TeamName;
            teamlist = teamlist + teamname + " , ";
        }
        @{if (teamlist.Length>1)
            {
                teamlist = teamlist.Substring(0, teamlist.Length - 2);
            }}
         
        <dd>@teamlist</dd>
</dl>
    </div>
    <div class="bottom-right" style="align-self:flex-start">
        <div style="font:message-box;font-weight:blod" >  
            @{if (Model.viewVolunteers.Portrait == null)
                {
                    <img id="opop" src="~/images/portrait/defaultportrait.png" align="left" width="190" height="210" display=inline>
                }
                else
                {
                    <img id="opop" src="~/images/portrait/@Model.viewVolunteers.Portrait" align="left" width="190" height="210" display=inline>
                }}
    </div>
     
</div>
<div class="pager">
    
</div> 
</body>
</html>

Areas/Management/Views/Volunteer/Edit.cshtml
@model Version1.Models.ApplicationUser

 

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>

<form sp-area="Management" asp-controller="Volunteer" asp-action="Edit" enctype="multipart/form-data">
    <div class="form-horizontal">
        <h4>ApplicationUser</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="Id" />
        <div class="form-group">
            <label class="col-md-2 control-label">User Portrait</label>
            <div class="col-md-10">
                <input type="file" id="NewsImagepp" value="Open file" title="Open file" accept=".JPG,.JPEG,.GIF,.PNG,.bmp" name="NewsImagepp" />
                <br>
                @{if (Model.Portrait == null)
                    {
                        <img id="opop" src="~/images/portrait/defaultportrait.png" align="left" width="190" height="210" display=inline>
                    }
                    else
                    {
                        <img id="opop" src="~/images/portrait/@Model.Portrait" align="left" width="190" height="210" display=inline>
                    }}

                <input type="hidden" asp-for="Portrait" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="gender" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="gender" class="form-control"><option>Male</option><option>Female</option></select>
            </div>
            <span asp-validation-for="gender" class="text-danger" />
        </div>
    
        <div class="form-group">
            <label asp-for="Age" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ConcurrencyStamp" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ConcurrencyStamp" class="form-control" />
                <span asp-validation-for="ConcurrencyStamp" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Email" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger" />
            </div>
        </div>
        
        <div class="form-group">
            <label asp-for="FirstName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="LastName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger" />
            </div>
        </div>
        
        <div class="form-group">
            <label asp-for="NormalizedEmail" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="NormalizedEmail" class="form-control" />
                <span asp-validation-for="NormalizedEmail" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="NormalizedUserName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="NormalizedUserName" class="form-control" />
                <span asp-validation-for="NormalizedUserName" class="text-danger" />
            </div>
        </div>
        
        <div class="form-group">
            <label asp-for="PhoneNumber" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger" />
            </div>
        </div> 
        <div class="form-group">
            <label asp-for="UserName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger" />
            </div>
        </div>
        <div class="form-group">  
           
    <label asp-for="EmailConfirmed" class="col-md-2 control-label"> Email Confirmed</label>
            <div class="col-md-10">
                <input asp-for="EmailConfirmed" style="width:35" type="checkbox" class="form-control" />
            </div>
</div>
        <div class="form-group">
                <label asp-for="PhoneNumberConfirmed" class="col-md-2 control-label"> Phone-Number Confirmed</label>
            <div class="col-md-10">
                <input asp-for="PhoneNumberConfirmed" style="width:35" type="checkbox" class="form-control" />
            </div>
            </div>
        <div class="form-group">
            <label asp-for="UserState" class="col-md-2 control-label">User State</label>
            <div class="col-md-10">               
            <select asp-for="UserState" class="form-control" ><option>Primary User</option><option>Contacted User</option><option>Zombie User</option></select>
            </div>
        </div>
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
     
</form>

<div>
    <a sp-area="Management" asp-controller="Volunteer" asp-action="Index">Back to List</a>
</div>


    @section Scripts {
        <script src="//code.jquery.com/jquery-1.12.4.min.js"></script>
        <script src="//rawgithub.com/indrimuska/jquery-editable-select/master/dist/jquery-editable-select.min.js"></script>
        <script src="/lib/ckeditor/ckeditor.js"></script>
        <link href="//rawgithub.com/indrimuska/jquery-editable-select/master/dist/jquery-editable-select.min.css" rel="stylesheet">


        <script>
    $(function () {
     
   var  getobjectpath= function (file) {
        var url = null;
        if (window.createObjectURL != undefined) {
            url = window.createObjectURL(file)
        } else if (window.URL != undefined) {
            url = window.URL.createObjectURL(file)
        } else if (window.webkitURL != undefined) {
            url = window.webkitURL.createObjectURL(file)
        }
        return url
    };
   $("#NewsImagepp").change(function () {
        var imagepath = getobjectpath(this.files[0]);
        if (imagepath != "") {
            $("#opop").hide;
            $("#opop").attr('src', imagepath);
            $("#opop").fadeIn(1000);
        }
   });
    });
        </script>
    }
</body>
</html>