ViewModels/RoleManage/Authorization_Object_Role.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Version1.Models;

namespace Version1.ViewModels.RoleManage
{
    //Configuration of Authorization Role and Authorization Objects

    public class Authorization_Object_Role_ViewModel
    {
        public List<Authorization_Object_Role> AuthorizationDone { get; set; }
        public List<IdentityRole> Roles { get; set; }
        public List<Authorization_Object> Authorization_Object { get; set; }

    }
}

Areas/Management/Controllers/Authorization_Object_RoleController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Version1.Models;
using Version1.ViewModels.RoleManage;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace Version1.Controllers
{
    [Area("Management")]
  //  [Authorize(Roles = "manager")]
    public class Authorization_Object_RoleController : Controller
    {
        //private UserManager<ApplicationUser> _userManager;
        //private RoleManager<IdentityRole> _roleManager;
        private readonly ApplicationDbContext _context;
        ViewModels.RoleManage.Authorization_Object_Role_ViewModel viewModel = new ViewModels.RoleManage.Authorization_Object_Role_ViewModel();
        public override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            // return;
            //if(ModelState.Count == 0)
            //{
            //    var areaname = filterContext.ActionDescriptor.RouteConstraints.Where(i => i.RouteKey == "area").First().RouteValue.ToString();
            //    var controllerName = filterContext.ActionDescriptor.RouteConstraints.Where(i => i.RouteKey == "controller").First().RouteValue.ToString();
            //    var actionName = filterContext.ActionDescriptor.Name;
            //    // var userId = _userManager.GetUserAsync(HttpContext.User).Id.ToString();
            //    var userId = "";
            //    var FullControllerName = areaname + "/" + controllerName;
            //    var username = filterContext.HttpContext.User.Identity.Name;
            //    if(username == null)
            //    {
            //        filterContext.Result = new ContentResult { Content = @"Sorry you don't have any aothrization." };
            //        return;
            //    }
            //    string itemrole;
            //    List<string> aa = new List<string>();
            //    if(username == "")
            //    { filterContext.Result = new ContentResult { Content = @"Sorry you don't have any aothrization." }; return; }
            //    else if(username != "")
            //    {
            //        //1.retrieving the role of the user from DB
            //        userId = _context.Users.Where(aaa => aaa.UserName == username).First().Id.ToString();
            //        foreach(var item in _context.UserRoles.Where(u => u.UserId == userId).ToList())
            //        {
            //            aa.Add(item.RoleId.ToString());
            //        }
            //        if(aa == null)
            //        {
            //            filterContext.Result = new ContentResult { Content = @"Sorry you don't have any aothrization." };
            //            return;
            //        }
            //        else if(aa.Count == 0)
            //        {
            //            filterContext.Result = new ContentResult { Content = @"Sorry you don't have any aothrization." };
            //            return;
            //        }
            //        if(_context.Authorization_Object.Where(N => N.ObjectType.ToUpper() == "FUNCTION").Where(N => N.ActionName.ToUpper() == actionName.ToUpper()).Where(N => N.FullControllerName.ToUpper() == FullControllerName.ToUpper()).Count() > 0)
            //        {
            //            //2.retrieving the role related to the ACTION from DB
            //            var Object_ID = _context.Authorization_Object.Where(N => N.ObjectType.ToUpper() == "FUNCTION").Where(N => N.ActionName.ToUpper() == actionName.ToUpper()).Where(N => N.FullControllerName.ToUpper() == FullControllerName.ToUpper()).FirstOrDefault().ID.ToString();
            //            List<Authorization_Object_Role> bb = _context.Authorization_Object_Role.Where(p => p.Authorization_Object_ID.ToString() == Object_ID).ToList();
            //            //3.contrast the two roles,find if they are consistent 
            //            if(bb == null)
            //            {
            //                filterContext.Result = new ContentResult { Content = @"Sorry you don't have any aothrization." };
            //                return;
            //            }
            //            else if(bb.Count == 0)
            //            {
            //                filterContext.Result = new ContentResult { Content = @"Sorry you don't have any aothrization." };
            //                return;
            //            }
            //            else
            //            {
            //                foreach(var item in bb)
            //                {
            //                    itemrole = item.RoleID.ToString();
            //                    if(aa.Contains(itemrole) == true)
            //                    {
            //                        filterContext.Result = filterContext.Result;
            //                        return;
            //                    }
            //                }
            //            }
            //        }
            //    }
            //    else
            //    {
            //        filterContext.Result = new ContentResult { Content = @"Sorry you don't have any aothrization." };
            //        return;
            //    }
            //}
        }
        public Authorization_Object_RoleController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Authorization_Object_Role
        public IActionResult Index()
        {
            viewModel.AuthorizationDone = _context.Authorization_Object_Role.ToList();
            viewModel.Authorization_Object = _context.Authorization_Object.ToList();
            viewModel.Roles = _context.Roles.ToList();
            return View("Index", viewModel);
        }

        [HttpGet]
        public ActionResult Update()
        {

            return View(viewModel);
        }
        [HttpPost]
        public ActionResult Update(Authorization_Object_Role_ViewModel gg)
        {
            if(ModelState.IsValid)
            {

                var all = from c in _context.Authorization_Object_Role select c;
                if(gg.AuthorizationDone != null)
                {
                    foreach(var item in gg.AuthorizationDone)
                    {
                        _context.Authorization_Object_Role.Add(new Authorization_Object_Role { RoleID = item.RoleID, Authorization_Object_ID = item.Authorization_Object_ID });
                    }
                }

                _context.Authorization_Object_Role.RemoveRange(all);
                int num = _context.SaveChanges();
                TempData["Message"] = num.ToString() + " Change have finished!";
                //TempData.Keep("Message");
            }
            // return Content("<script language='javascript' type='text/javascript'>alert('Hello world!');</script>");
            return RedirectToAction("Index");

        }
    }
}

Areas/Management/Views/Authorization_Object_Role/Index.cshtml
@model Authorization_Object_Role_ViewModel

<h1>Matching Authorization Objects and User Roles</h1>

@*<a asp-area="Management" asp-controller="Authorization_Object" asp-action="Index" target="_blank">Management of Objects</a>&nbsp&nbsp*@
<a asp-area="Management" asp-controller="Authorization_Object" asp-action="Create" target="_blank">Add New Object to Authorize</a>
<form class="form-horizontal" id="formAuthorizationUpdate" asp-route-area="management" asp-controller="Authorization_Object_Role" asp-action="Update" method="post" role="form">

    <table id="tblUsersRoles" class="table">
        <thead>
            <tr>
                <th>All Authorization Objects \ All Roles</th>
                @foreach(var role in Model.Roles)
                {
                    <th>
                        @role.Name
                        <input value="@role.Name " hidden />
                    </th>
                }
            </tr>
        </thead>

        <tbody>
            @foreach(var item in Model.Authorization_Object)
            {
                <tr>
                    <td>
                        <a asp-route-area="management" asp-controller="Authorization_Object" asp-action="Details" asp-route-id="@item.ID" target="_blank">@item.ObjectName</a>

                        @* this value will be insert in the dict as a key *@
                        <input value="@item.ID" hidden />
                    </td>
                    @foreach(var val in Model.Roles)
                    {
                        <td>
                            @if(Model.AuthorizationDone.Where(p => p.RoleID == val.Id).Where(p => p.Authorization_Object_ID == @item.ID).ToList().Count > 0)
                            {
                                <div class="btneditAuthorization btn btn-sm glyphicon glyphicon-ok" role="checkbox" value="true" itemid="@val.Id" name="@item.ID"></div>
                            }
                            else
                            {
                                <div class="btneditAuthorization btn btn-sm glyphicon glyphicon-remove" role="checkbox" value="false" itemid="@val.Id" name="@item.ID"></div>
                            }

                        </td>
                    }
                </tr>
            }
        </tbody>
    </table>

    <button id="submit" class="btn btn-default btnSubmit" role="button">Save Configuration</button>
</form>

@section scripts{
    <script type="text/javascript">

        $(document).ready(function () {
            $('.btneditAuthorization').click(function (event) {
                event.preventDefault();
                if ($(this).attr('value') == 'true') {
                    $(this).attr('value', 'false');
                    $(this).removeClass('glyphicon-ok').addClass('glyphicon-remove');
                }
                else if ($(this).attr('value') == 'false') {
                    $(this).attr('value', 'true');
                    $(this).removeClass('glyphicon-remove').addClass('glyphicon-ok');
                }
            });
        });
    </script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#formAuthorizationUpdate').on('click', '#submit', function (event) {
                event.preventDefault();
                var dict = [];
                $('.btneditAuthorization').each(function (index) {
                    if ($(this).attr('value') == 'true') {
                        var item = { RoleID: $(this).attr('itemid'), Authorization_Object_ID: $(this).attr('name') };
                        dict.push(item);
                    }
                    else { }
                });
                var postUrl = '/Management/Authorization_Object_Role/Update';
                // Post and return to the given view is there is nothing to return.
                $.post(postUrl, { AuthorizationDone: dict }, function (result) {
                    window.location.assign("/Management/Authorization_Object_Role/Index");
                    alert('You have finished change!');
                });

            });
        });

    </script>

}